# Generated by Django 6.0.3 on 2026-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
