# Generated by Django 6.0.3 on 2026-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='department',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
